### ISSUE TITLE
Erro ao recuperar os veículos de uma linha

### ISSUE THREAD

**Issue by hcordeiro** [tOOlmaker-equalsp/apiStransTHE#7]
Reparei que a maneira da API responder que não existem ônibus em uma determinada linha é responder o request GET /veiculos?linha=[codigoLinha] com o código 400. Não sei se é a melhor maneira, mas pelo menos por agora, seria interessante adicionar o tratamento para não lançar uma Exception para o usuário do wrapper.

**Comment by erickpassos** [comment]
É uma boa ideia tratar isso, mas acredito que deve ser levantada uma Exception específica indicando o que é exatamente que acontece (e o usuário trata essa na aplicação).

**Comment by jweslley** [comment]
qdo retorna qq resposta com status 400, ja é lancada um excecao `InthegraException` capturada pelo `InthegraClient` contendo o codigo do erro e a mensagem de erro enviada pela API do Inthegra.

Referencias:
- [InthegraClient](https://github.com/tOOlmaker-equalsp/apiStransTHE/blob/f8a75fcca3153a901b4a65bc1c0e43209ffce431/src/main/java/com/equalsp/stransthe/InthegraClient.java#L183)
- [CachedInthegraService](https://github.com/tOOlmaker-equalsp/apiStransTHE/blob/0a1ceff858d8fee9181536222a80ecb9b83668b4/src/main/java/com/equalsp/stransthe/CachedInthegraService.java#L80)

**Comment by hcordeiro** [comment]
Minha dúvida é, se no momento, uma Exception é a melhor resposta para isso.

**Comment by jweslley** [comment]
Neste caso, se nao há onibus para uma linha qualquer, o ideal seria retornar uma lista vazia. Exceto qdo a linha nao existe.

**Comment by hcordeiro** [comment]
Exatamente, o que quis dizer no primeiro post foi que a API não deixa claro se a linha não existe ou simplesmente não há ônibus "rodando" no momento da requisição. Dessa maneira, eu acho que seria melhor retornar uma lista vazia, poderíamos verificar se a linha existe no "getLinhas". 

Essa seria uma solução paliativa enquanto a API não retorna algo consistente.

**Comment by erickpassos** [comment]
Fiz a correção do código de retorno (que agora é 404). Semana que vem podemos verificar a melhor forma de disponibilizar a lista vazia.

**Comment by cyny39** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
Johnnyfdev, @frankdors, @bergginu, @noghartt, @carlossgabriel, @joivo, @bbertolani, @guilhermesteves, @idMauricio, @diogobest, @tchaguitos, @jvsouto, @rpereira15, @fabioper, @lbs-rodrigo, @robertoduessmann, @jooaodias, @VictorhMalheiro, @thawankeane, @rafaelandrade74
